# Generated by Django 2.1.1 on 2018-09-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('codAsesoria', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fechaAsesoria', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=300)),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Asesoria')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigoCurso', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombreCurso', models.CharField(max_length=50)),
                ('seccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codProfesor', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombrepProfesor', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('A', 'Alumno'), ('P', 'Profesor'), ('S', 'SECRETARIA ACADEMICA')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='codProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profesor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombreAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Usuario'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='codCurso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Curso'),
        ),
    ]
